FROM ubuntu:latest

RUN apt-get update && apt-get install -y curl jq

COPY country_lookup.sh /app/country_lookup.sh

RUN chmod +x /app/country_lookup.sh

WORKDIR /app

ENTRYPOINT ["/app/country_lookup.sh"]

CMD []
